# Generated by Django 2.0.3 on 2018-04-28 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_project_platform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='goals',
        ),
        migrations.RemoveField(
            model_name='project',
            name='outcomes',
        ),
        migrations.RemoveField(
            model_name='project',
            name='process',
        ),
        migrations.AddField(
            model_name='project',
            name='readme',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
