# Generated by Django 2.0.3 on 2018-04-29 10:35

from django.db import migrations, models
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_auto_20180429_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='img',
            field=models.ImageField(storage=gdstorage.storage.GoogleDriveStorage(), upload_to='images'),
        ),
        migrations.AlterField(
            model_name='project',
            name='readme',
            field=models.FileField(null=True, storage=gdstorage.storage.GoogleDriveStorage(), upload_to='readmes'),
        ),
    ]
